import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { couponHint, normalizeCouponCode } from '../src/vacation/coupons.mjs';

assert.equal(normalizeCouponCode(' ts launch 001 '), 'TSLAUNCH001');
assert.equal(couponHint('TS-LAUNCH-001'), 'TS-...001');

const checkoutCouponApi = await readFile(new URL('../api/checkout-coupon.mjs', import.meta.url), 'utf8');
const addOnsCheckoutHtml = await readFile(new URL('../addons-checkout.html', import.meta.url), 'utf8');
const ownerMediaCheckoutHtml = await readFile(new URL('../owner-media-checkout.html', import.meta.url), 'utf8');
const orderSuccessHtml = await readFile(new URL('../order-success.html', import.meta.url), 'utf8');
const createPaymentIntentApi = await readFile(new URL('../api/create-payment-intent.mjs', import.meta.url), 'utf8');
assert(!checkoutCouponApi.includes("from 'stripe'"));
assert(!checkoutCouponApi.includes('new Stripe'));
assert(!checkoutCouponApi.includes('paymentIntents'));
assert(!checkoutCouponApi.includes('subscriptions.create'));
assert(checkoutCouponApi.includes('collaboratorInviteToken'));
assert(checkoutCouponApi.includes("status: 'collaborator_coupon_redeemed'"));
assert(checkoutCouponApi.includes('collaboratorAccessAddOns(body, plan)'));
assert(checkoutCouponApi.includes("status: 'owner_media_coupon_redeemed'"));
assert(checkoutCouponApi.includes("product === 'owner_media_addons'"));
assert(checkoutCouponApi.includes('amountWaivedCents: originalAmountCents'));
assert(addOnsCheckoutHtml.includes('Access add-on coupon'));
assert(addOnsCheckoutHtml.includes('$0 after valid coupon'));
assert(addOnsCheckoutHtml.includes('Redeem coupon'));
assert(addOnsCheckoutHtml.includes('Website editing is separate and FREE'));
assert(addOnsCheckoutHtml.includes('id="accessTotal"'));
assert(addOnsCheckoutHtml.includes('One collaborator is added per checkout.'));
assert(addOnsCheckoutHtml.includes('isUnlimited() ? 2700 : 1500'));
assert(!addOnsCheckoutHtml.includes('<strong>$49</strong>'));
assert(!addOnsCheckoutHtml.includes('<strong>$73</strong>'));
assert(!addOnsCheckoutHtml.includes('Up to 3 active Telegram collaborators'));
assert(ownerMediaCheckoutHtml.includes('Owner media add-ons'));
assert(ownerMediaCheckoutHtml.includes('This checkout is separate from adding a Telegram collaborator.'));
assert(ownerMediaCheckoutHtml.includes("params.get('session') || params.get('token')"));
assert(ownerMediaCheckoutHtml.includes('/api/onboarding-session?session='));
assert(ownerMediaCheckoutHtml.includes('prefillOwnerContact(data.session || {})'));
assert(ownerMediaCheckoutHtml.includes("action: 'create_owner_media_payment_intent'"));
assert(ownerMediaCheckoutHtml.includes("action: 'complete_staging_owner_media_checkout'"));
assert(ownerMediaCheckoutHtml.includes("action: 'redeem_owner_media_coupon'"));
assert(ownerMediaCheckoutHtml.includes('Media add-on coupon'));
assert(ownerMediaCheckoutHtml.includes('function ownerMediaSuccessUrl()'));
assert(ownerMediaCheckoutHtml.includes("params.set('ownerName', ownerName)"));
assert(orderSuccessHtml.includes('id="intro"'));
assert(orderSuccessHtml.includes("intro.classList.add('hidden')"));
assert(orderSuccessHtml.includes("Photo and video upload access has been added for ${ownerName || 'the owner account'}."));
assert(!orderSuccessHtml.includes('Photo and video upload access has been added for the selected vacation scope.'));
assert(createPaymentIntentApi.includes("body.action === 'create_owner_media_payment_intent'"));
assert(createPaymentIntentApi.includes("body.action === 'complete_staging_owner_media_checkout'"));

console.log('checkout coupon smoke passed');
